version: "3.9"

services:
  eureka-server:
    container_name: eureka-server
    build:
      context: ../../
      dockerfile: infra/docker/Dockerfile
    image: eureka-server
    ports:
      - "8761:8761"
